# Generated by Django 4.0.3 on 2023-02-27 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_algorithm_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='algorithm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.algorithm'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.target'),
        ),
    ]
