# Generated by Django 4.0.3 on 2023-03-14 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_alter_simulation_algorithm_alter_simulation_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.IntegerField(verbose_name='数据')),
                ('outcome', models.IntegerField(verbose_name='模拟结果')),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.algorithm')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.target')),
            ],
        ),
    ]
