# Generated by Django 4.0.3 on 2023-03-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='outcome',
            field=models.IntegerField(blank=True, null=True, verbose_name='模拟结果'),
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
