# Generated by Django 4.0.3 on 2023-03-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_simulation_outcome_delete_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='time',
            field=models.DateField(blank=True, null=True, verbose_name='时间参数'),
        ),
    ]
